name: Deploy Lambda Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: zip source code
      uses: montudor/action-zip@v1
      with:
        args: zip -r serverless-lambda-staging-hello.zip ./ -x ''*.husky*''
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Deploy lambda function
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws lambda update-function-code --function-name serverless-lambda-staging-hello --zip-file fileb://serverless-lambda-staging-hello.zip --region ap-south-1
    - name: Update lambda function environment variables
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        LAMBDA_VAR: ${{ secrets.LAMBDA_VAR }}
      run: aws lambda update-function-configuration --function-name serverless-lambda-staging-hello --environment "Variables=$LAMBDA_VAR"